"""empty message

Revision ID: 0fd1f5ee0bec
Revises: 51658467b4bf
Create Date: 2018-02-25 23:00:24.991203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd1f5ee0bec'
down_revision = '51658467b4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail', 'email')
    # ### end Alembic commands ###
