"""empty message

Revision ID: 1233098328ad
Revises: 31dc5a9428de
Create Date: 2017-10-21 14:53:25.715785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1233098328ad'
down_revision = '31dc5a9428de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_member', sa.Column('owner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_member', 'owner')
    # ### end Alembic commands ###
