"""empty message

Revision ID: 2fe6c9f5d4e9
Revises: c421fe2fbad4
Create Date: 2017-10-21 16:25:40.028102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe6c9f5d4e9'
down_revision = 'c421fe2fbad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personal_organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_profile_organization_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['personal_organization_id'])
    op.drop_constraint('user_profile_organization_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'organization', ['personal_organization_id'], ['id'])
    op.drop_column('user', 'profile_organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_profile_organization_id_fkey', 'user', 'organization', ['profile_organization_id'], ['id'])
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_profile_organization_id_key', 'user', ['profile_organization_id'])
    op.drop_column('user', 'personal_organization_id')
    # ### end Alembic commands ###
