"""empty message

Revision ID: 31dc5a9428de
Revises: f0c513ad928c
Create Date: 2017-10-21 14:49:10.246583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dc5a9428de'
down_revision = 'f0c513ad928c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('personal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'personal')
    # ### end Alembic commands ###
