"""empty message

Revision ID: 613e287999e2
Revises: cf5457e5701b
Create Date: 2017-11-27 22:57:34.889970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613e287999e2'
down_revision = 'cf5457e5701b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_validator', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_validator', 'error_message')
    # ### end Alembic commands ###
