"""empty message

Revision ID: b3ac40388cc2
Revises: 2fe6c9f5d4e9
Create Date: 2017-10-30 01:12:44.556275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3ac40388cc2'
down_revision = '2fe6c9f5d4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gmail', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail', 'data')
    op.drop_table('google_drive')
    # ### end Alembic commands ###
