"""empty message

Revision ID: c421fe2fbad4
Revises: e9d6685d1cff
Create Date: 2017-10-21 15:41:14.880448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c421fe2fbad4'
down_revision = 'e9d6685d1cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('secret', sa.Boolean(), nullable=True))
    op.drop_column('endpoint', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('endpoint', 'secret')
    # ### end Alembic commands ###
