"""empty message

Revision ID: e8934b18a8b4
Revises: 36f5b87d2121
Create Date: 2018-03-08 21:44:54.329427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8934b18a8b4'
down_revision = '36f5b87d2121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('recaptcha', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint', 'recaptcha')
    # ### end Alembic commands ###
