"""empty message

Revision ID: f0c513ad928c
Revises: 90266e12a3f3
Create Date: 2017-10-21 13:24:31.072121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c513ad928c'
down_revision = '90266e12a3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('endpoint', sa.Column('uuid', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'endpoint', ['uuid'])
    op.drop_column('endpoint', 'slug')
    op.add_column('organization', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('organization_slug_key', 'organization', type_='unique')
    op.create_unique_constraint(None, 'organization', ['name'])
    op.drop_column('organization', 'slug')
    op.add_column('post', sa.Column('uuid', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'post', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'uuid')
    op.add_column('organization', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization', type_='unique')
    op.create_unique_constraint('organization_slug_key', 'organization', ['slug'])
    op.drop_column('organization', 'name')
    op.add_column('endpoint', sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'endpoint', type_='unique')
    op.drop_column('endpoint', 'uuid')
    op.drop_column('endpoint', 'name')
    # ### end Alembic commands ###
